version: 2.1

defaults:
  ci: &ci
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /[0-9]{14}.*/

workflows:
  version: 2
  test:
    jobs:
      - test
  release:
    jobs:
      - ci:
          <<: *ci
          name: ci/aws/public
          provider: aws
      - ci:
          <<: *ci
          name: ci/aws/private
          provider: aws
          args: Private=Yes
      - ci:
          <<: *ci
          name: ci/kaws
          provider: kaws

jobs:
  ci:
    parameters:
      provider:
        type: string
      args:
        type: string
        default: ""
    docker:
      - image: circleci/golang:1.12
    environment:
      PROVIDER: << parameters.provider >>
      ARGS: << parameters.args >>
    steps:
      - checkout
      - ci-dependencies
      - ci-install
      - ci-test
      - ci-uninstall
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/convox/rack
    steps:
      - checkout
      - run: go install ./cmd/convox
      - run: make test
      - run: curl -s https://codecov.io/bash | bash
          
commands:
  ci-dependencies:
    steps:
      - run: ci/dependencies.sh
  ci-install:
    steps:
      - run:
          command: ci/install.sh
          no_output_timeout: 20m
  ci-test:
    steps:
      - run:
          command: ci/test.sh
          no_output_timeout: 20m
  ci-uninstall:
    steps:
      - run: ci/uninstall.sh
